import React,{useEffect,useRef,useState} from 'react';
import type {Home,Product} from '../lib/model';
import {barcodeProduct} from '../lib/shopping-tools';
type Controls={stop:()=>void};
type Reader={decodeFromConstraints:(constraints:MediaStreamConstraints,video:HTMLVideoElement,callback:(result:{getText:()=>string}|undefined,error:any,controls:Controls)=>void)=>Promise<Controls>};
const defaultReader=async():Promise<Reader>=>{const {BrowserMultiFormatReader}=await import('@zxing/browser');return new BrowserMultiFormatReader();};
export default function BarcodeScanner({home,busy,onProduct,onAssign,readerFactory=defaultReader}:{home:Home;busy:boolean;onProduct:(p:Product)=>void;onAssign:(id:string,code:string)=>Promise<boolean>;readerFactory?:()=>Promise<Reader>}){
 const [open,setOpen]=useState(false),[camera,setCamera]=useState(false),[code,setCode]=useState(''),[searched,setSearched]=useState(''),[productId,setProductId]=useState(''),[error,setError]=useState('');const video=useRef<HTMLVideoElement>(null);
 useEffect(()=>{if(!camera||!video.current)return;let cancelled=false,controls:Controls|undefined;const element=video.current;
  void readerFactory().then(async reader=>{if(cancelled)return;controls=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'}},audio:false},element,(result,_error,control)=>{if(cancelled||!result)return;const value=result.getText();if(!/^\d{8,14}$/.test(value)){setError('Ese código no es un código de producto.');return;}control.stop();setCode(value);setSearched(value);setCamera(false);});if(cancelled)controls.stop();}).catch(()=>{if(!cancelled){setError('No se pudo abrir la cámara. Puedes escribir el código o permitir el acceso a la cámara en tu navegador.');setCamera(false);}});
  return()=>{cancelled=true;controls?.stop();const stream=element.srcObject as MediaStream|null;stream?.getTracks?.().forEach(track=>track.stop());element.srcObject=null;};
 },[camera,readerFactory]);
 const product=barcodeProduct(home,searched);
 return <section className="barcode-tool"><button onClick={()=>{setOpen(!open);setCamera(false);setError('')}}>{open?'Cerrar lector':'📷 Buscar por código de barras'}</button>{open&&<div><p className="secondary">Escanea el código o escríbelo. La primera vez puedes asociarlo a uno de tus productos.</p><button disabled={camera} onClick={()=>{setError('');setCamera(true)}}>Abrir cámara</button>{camera&&<><video ref={video} muted playsInline className="barcode-video"/><button onClick={()=>setCamera(false)}>Detener cámara</button></>}<form onSubmit={e=>{e.preventDefault();setError('');if(!/^\d{8,14}$/.test(code.trim())){setError('Escribe entre 8 y 14 dígitos.');return;}setSearched(code.trim());setCamera(false);}}><label>Código de barras<input inputMode="numeric" maxLength={14} value={code} onChange={e=>setCode(e.target.value)}/></label><button>Buscar código</button></form>{searched&&(product?<div className="barcode-result"><strong>{product.name}</strong><button disabled={busy} onClick={()=>{setCamera(false);onProduct(product)}}>Agregar este producto</button></div>:<form onSubmit={async e=>{e.preventDefault();if(await onAssign(productId,searched)){setProductId('');setError('');}}}><p>Este código todavía no está asociado.</p><label>Producto para asociar<select required value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Selecciona un producto</option>{home.products.filter(p=>p.name).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button disabled={busy||!productId}>Guardar código en producto</button></form>)}{error&&<p role="alert" className="form-error">{error}</p>}</div>}</section>;
}
