import React,{useEffect,useRef,useState} from 'react';
import {money} from '../lib/model';
import {priceCandidates} from '../lib/photo-shopping';
type ReadPhoto=(file:File,onProgress:(progress:number)=>void)=>Promise<string>;
export default function PhotoShopping({busy,upload,readPhoto,onPrice,onProduct}:{busy:boolean;upload:(file:File)=>Promise<string>;readPhoto:ReadPhoto;onPrice:(amount:number)=>Promise<boolean>;onProduct:(name:string,quantity:number,price:number|null,image:string)=>Promise<boolean>}){
 const [open,setOpen]=useState(false),[mode,setMode]=useState<'price'|'product'>('price'),[image,setImage]=useState(''),[preview,setPreview]=useState(''),[reading,setReading]=useState(false),[progress,setProgress]=useState(0),[candidates,setCandidates]=useState<ReturnType<typeof priceCandidates>>([]),[amount,setAmount]=useState(''),[name,setName]=useState(''),[quantity,setQuantity]=useState('1'),[error,setError]=useState(''),[notice,setNotice]=useState('');const operation=useRef(0);const active=useRef(true);
 useEffect(()=>{active.current=true;return()=>{active.current=false;operation.current++;}},[]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 function reset(){operation.current++;setImage('');setPreview('');setCandidates([]);setAmount('');setName('');setQuantity('1');setError('');setReading(false);setNotice('');}
 async function select(file:File|undefined){if(!file)return;reset();const token=operation.current;setReading(true);setProgress(0);if(!/^image\//.test(file.type)||file.size>20000000){setError('Usa una foto de menos de 20 MB.');setReading(false);return;}setPreview(URL.createObjectURL(file));try{
  if(mode==='product'){const photo=await upload(file);if(token===operation.current&&active.current)setImage(photo);}
  else{const text=await readPhoto(file,value=>{if(token===operation.current&&active.current)setProgress(value)});if(token!==operation.current||!active.current)return;const prices=priceCandidates(text);setCandidates(prices);if(prices.length===1)setAmount(String(prices[0].amount));if(!prices.length)setError('No pude leer el precio. Puedes escribirlo abajo o tomar otra foto.');}
 }catch{if(token===operation.current&&active.current)setError(mode==='product'?'No se pudo guardar la foto. Prueba con JPG o PNG.':'No se pudo leer la foto. Puedes escribir el monto o intentarlo de nuevo.');}finally{if(token===operation.current&&active.current)setReading(false);}}
 return <section className="photo-shopping"><button onClick={()=>{if(open)reset();setOpen(!open)}}>📷 {open?'Cerrar foto rápida':'Foto rápida'}</button>{open&&<div><div className="mode-tabs"><button disabled={reading||busy} className={mode==='price'?'selected':''} onClick={()=>{reset();setMode('price')}}>Foto del precio</button><button disabled={reading||busy} className={mode==='product'?'selected':''} onClick={()=>{reset();setMode('product')}}>Foto del producto</button></div><p className="secondary">{mode==='price'?'Fotografía de cerca la etiqueta. Revisa el monto antes de sumarlo.':'Toma la foto y completa el nombre y el precio para agregarlo al carrito.'}</p><label className="upload-label">📷 Tomar foto o elegir imagen<input aria-label="Foto rápida" type="file" accept="image/*" capture="environment" disabled={reading||busy} onChange={e=>{void select(e.target.files?.[0]);e.target.value=''}}/></label>{preview&&<img className="photo-preview" src={preview} alt={mode==='price'?'Etiqueta fotografiada':'Producto fotografiado'}/ >}{reading&&<p role="status">{mode==='price'?`Leyendo el precio… ${Math.round(progress*100)}%`:'Preparando la foto…'}</p>}{mode==='price'?<><div className="price-candidates">{candidates.map(p=><button key={p.amount} disabled={reading||busy} onClick={()=>setAmount(String(p.amount))}>{money(p.amount)}</button>)}</div>{candidates.length>1&&<p>Encontré varios números. Selecciona el precio correcto.</p>}<form onSubmit={async e=>{e.preventDefault();setError('');setNotice('');const value=Number(amount);if(!amount||!Number.isFinite(value)||value<=0){setError('Revisa el monto.');return;}if(await onPrice(value)){reset();setNotice(`${money(value)} agregado a la calculadora.`);}}}><label>Monto a sumar<input aria-label="Monto de la foto" type="number" min="0.01" max="10000000" step="any" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button disabled={busy||reading||!amount} className="primary">{amount?`Sumar ${money(Number(amount))}`:'Sumar a la calculadora'}</button></form></>:image&&<form onSubmit={async e=>{e.preventDefault();setError('');setNotice('');if(await onProduct(name,Number(quantity),amount===''?null:Number(amount),image)){reset();setNotice('Producto agregado al carrito.');}}}><label>Nombre del producto<input required maxLength={500} value={name} onChange={e=>setName(e.target.value)}/></label><div className="form-two"><label>Cantidad<input type="number" min="0.001" max="100000" step="any" required value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Precio por unidad (opcional)<input type="number" min="0" step="any" value={amount} onChange={e=>setAmount(e.target.value)}/></label></div><button disabled={busy||reading||!name.trim()} className="primary">Agregar producto al carrito</button></form>}{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status">{notice}</p>}</div>}</section>;
}
