import {Home, Product} from './model';
export const locations=['Alacena','Refrigeradora','Congelador','Limpieza','Baño','Mascotas'];
export type Lot={id:string;quantity:number;expiry:string};
export const stock=(p:Product):number|undefined=>p.pantryLots===undefined?undefined:(p.pantryLots as Lot[]).reduce((s,l)=>s+l.quantity,0);
export function replenish(p:Product){if(p.autoRestock&&stock(p)!==undefined&&stock(p)!<=Number(p.minimumStock||0)){p.purchased=false;p.runningLow=true;}}
export function consume(p:Product,amount:number){if(!Number.isFinite(amount)||amount<=0)throw Error('Cantidad inválida');let remaining=Math.min(amount,stock(p)||0);p.pantryLots=[...(p.pantryLots||[])].sort((a:Lot,b:Lot)=>(a.expiry||'9999').localeCompare(b.expiry||'9999')).map((l:Lot)=>{const used=Math.min(l.quantity,remaining);remaining-=used;return {...l,quantity:Math.round((l.quantity-used)*1000000)/1000000}}).filter((l:Lot)=>l.quantity>0);replenish(p);}
export function addStock(p:Product,quantity:number,expiry='',id:string=crypto.randomUUID()){if(!Number.isFinite(quantity)||quantity<=0||quantity>100000)throw Error('Revisa la cantidad');p.pantryLots=[...(p.pantryLots||[]),{id,quantity,expiry}];replenish(p);}
export function receivePurchase(h:Home,receiptId:string,entries:{productId:string;quantity:number;location:string;expiry:string}[]){const receipt=h.history.find(r=>r.id===receiptId);if(!receipt)throw Error('Compra no encontrada');if(receipt.pantryReceived)return;const allowed=new Set(receipt.items.map((i:any)=>i.productId).filter(Boolean));const seen=new Set();for(const e of entries){if(!allowed.has(e.productId)||seen.has(e.productId))throw Error('Producto inválido');seen.add(e.productId);const p=h.products.find(p=>p.id===e.productId);if(!p)continue;if(!locations.includes(e.location))throw Error('Ubicación inválida');if(e.quantity>0){addStock(p,e.quantity,e.expiry,receiptId+':'+p.id);p.pantryLocation=e.location;}}receipt.pantryReceived=true;}
export function unitPrice(price:number,size:number,unit:string){if(!Number.isFinite(price)||price<0||!Number.isFinite(size)||size<=0)return null;const factor=unit==='g'||unit==='ml'?0.001:1;return {value:price/(size*factor),dimension:unit==='g'||unit==='kg'?'kg':unit==='ml'||unit==='l'?'l':'unidad'};}
export function quickAdd(h:Home,name:string,quantity:number,price:number|null,id:string){name=name.trim();if(!name||name.length>500||!Number.isFinite(quantity)||quantity<=0||quantity>100000||price!==null&&(!Number.isFinite(price)||price<0))throw Error('Revisa el nombre, cantidad y precio');let p=h.products.find(p=>p.name.trim().toLocaleLowerCase()===name.toLocaleLowerCase());if(!p){p={id,name,image:'',icon:'🛍️',storeId:h.cartStoreId,sectionId:'',purchased:false,frequent:false,finished:false,price,lastPrice:null,lastDate:'',notes:''};h.products.push(p);}const item=h.cart.find(i=>i.productId===p!.id);if(item){if(item.quantity+quantity>100000)throw Error('Cantidad demasiado grande');item.quantity+=quantity;if(price!==null)item.price=price;}else h.cart.push({productId:p.id,quantity,price,discount:0});return p.id;}
