import {test} from 'node:test';
import assert from 'node:assert/strict';
import {repeatPurchase,pricesByStore,routeSections} from '../../lib/shopping';
import {calculate,replaceNumber} from '../../lib/calculator';
import {mergeHomes,copy} from '../merge';
import {SyncEngine,type RemoteHome} from '../sync-engine';
import {checkout,valid} from '../home-actions';
import type {Home} from '../../lib/model';
import type {CachedHome} from '../offline-cache';
const entity=(id:string)=>({id,name:id,image:'',icon:''});
function sample():Home{return {products:[{...entity('soap'),storeId:'shop',sectionId:'care',purchased:true,finished:false,frequent:false,price:100,lastPrice:100,lastDate:'',notes:''},{...entity('rice'),storeId:'shop',sectionId:'food',purchased:false,finished:false,frequent:false,price:200,lastPrice:200,lastDate:'',notes:''}],stores:[entity('shop'),entity('other')],sections:[{...entity('care'),order:2},{...entity('food'),order:1}],lists:[],cover:'',cart:[],calculatorExpression:'',budget:null,cartStoreId:'shop',cartListId:'',history:[]};}
function setup(){let remote:RemoteHome={home:sample(),revision:1};let cached:CachedHome|undefined;let online=true,fail=false;const engine=new SyncEngine({read:async()=>{if(fail)throw Error('network');return copy(remote)},commit:async edit=>{if(fail)throw Error('network');const next=edit(copy(remote));if(next)remote={home:copy(next),revision:remote.revision+1};return copy(remote)}},{read:async()=>cached&&copy(cached),write:async value=>{cached=copy(value)}},()=>online);return {engine,setOnline:(value:boolean)=>online=value,setFail:(value:boolean)=>fail=value,remote:()=>remote,editRemote:(edit:(h:Home)=>void)=>{edit(remote.home);remote.revision++},cache:()=>cached};}
test('repeat a purchase ignores deleted products and calculator rows and deduplicates',()=>{const h=sample(),receipt={storeId:'shop',storeName:'Shop',date:'2026-10-07T12:00:00Z',items:[{productId:'soap'},{productId:'soap'},{productId:'deleted'},{productId:null}]};const list=repeatPurchase(h,receipt,'new-list');assert.deepEqual(list.productIds,['soap']);assert.equal(list.completed,false);assert.equal(list.storeId,'shop');assert.throws(()=>repeatPurchase(h,{...receipt,items:[{productId:null}]},'x'));});
test('compare the latest actual discounted price per unit for each store',()=>{const h=sample();h.history=[{date:'2026-10-01',storeId:'shop',storeName:'Shop',items:[{productId:'soap',quantity:2,price:150,discount:20}]},{date:'2026-10-07',storeId:'shop',storeName:'Shop',items:[{productId:'soap',quantity:2,price:100,discount:10}]},{date:'2026-10-06',storeId:'other',storeName:'Other',items:[{productId:'soap',quantity:1,price:90,discount:0}]}];assert.deepEqual(pricesByStore(h,'soap').map(p=>p.price),[90,95]);assert.equal(pricesByStore(h,'soap')[1].date,'2026-10-07');});
test('route is saved per store with new sections falling back to original order',()=>{const h=sample();h.storeRoutes={shop:['care']};assert.deepEqual(routeSections(h,'shop').map(s=>s.id),['care','food']);assert.deepEqual(routeSections(h,'other').map(s=>s.id),['food','care']);});
test('correct a previous amount without changing multiplication, signs or parentheses',()=>{assert.equal(replaceNumber('2500+3500*2+',1,'4000'),'2500+4000*2+');assert.equal(calculate(replaceNumber('2500+3500*2+',1,'4000'),true).value,10500);assert.equal(replaceNumber('(2500-3500)/2',0,'4500'),'(4500-3500)/2');assert.throws(()=>replaceNumber('2500/2',1,'0'));assert.throws(()=>replaceNumber('1+2',0,'3+5'));});
test('independent edits on the same product and other products combine',()=>{const b=sample(),l=copy(b),r=copy(b);l.products[0].runningLow=true;l.products[0].purchased=false;r.products[0].notes='other edit';r.products[1].price=300;const merged=mergeHomes(b,l,r);assert.equal(merged.conflicts.length,0);assert.equal(merged.home.products[0].runningLow,true);assert.equal(merged.home.products[0].notes,'other edit');assert.equal(merged.home.products[1].price,300);});
test('same field changes and delete-versus-edit are explicit conflicts',()=>{const b=sample(),l=copy(b),r=copy(b);l.budget=1000;r.budget=2000;l.products=l.products.filter(p=>p.id!=='soap');r.products[0].price=80;const merged=mergeHomes(b,l,r);assert.deepEqual(merged.conflicts.map(c=>c.path).sort(),['/budget','/products/soap']);assert.equal(mergeHomes(b,l,r,{'/budget':'remote','/products/soap':'remote'}).home.products[0].price,80);});
test('offline changes survive reload and merge when connection returns',async()=>{const f=setup(),first=await f.engine.load();f.setOnline(false);first.home.products[0].runningLow=true;first.home.products[0].purchased=false;const saved=await f.engine.save({...first,action:'save'},h=>h);assert.equal(saved.pending,true);assert.equal(f.cache()?.home.products[0].runningLow,true);f.editRemote(h=>h.products[1].price=350);f.setOnline(true);const synced=await f.engine.load();assert.equal(synced.pending,false);assert.equal(synced.home.products[0].runningLow,true);assert.equal(synced.home.products[1].price,350);});
test('offline conflict holds changes until chosen, preserving unrelated edits',async()=>{const f=setup(),first=await f.engine.load();f.setOnline(false);first.home.budget=1000;first.home.products[0].notes='my note';await f.engine.save(first,h=>h);f.editRemote(h=>{h.budget=2000;h.products[1].notes='sister note'});f.setOnline(true);await f.engine.load();assert.equal(f.engine.status.conflicts.length,1);assert.equal(f.cache()?.pending,true);await f.engine.resolve({'/budget':'remote'});assert.equal(f.remote().home.budget,2000);assert.equal(f.remote().home.products[0].notes,'my note');assert.equal(f.remote().home.products[1].notes,'sister note');});
test('a failed network commit keeps a durable pending change for retry',async()=>{const f=setup(),first=await f.engine.load();first.home.budget=5000;f.setFail(true);const saved=await f.engine.save(first,h=>h);assert.equal(saved.pending,true);assert.equal(f.cache()?.home.budget,5000);f.setFail(false);await f.engine.load();assert.equal(f.remote().home.budget,5000);assert.equal(f.cache()?.pending,false);});
test('offline checkout is saved once, resets cart, clears running-low flag',async()=>{const f=setup(),first=await f.engine.load();first.home.cart=[{productId:'soap',price:100,quantity:2,discount:10}];first.home.products[0].runningLow=true;const saved=await f.engine.save(first,h=>h);f.setOnline(false);const done=await f.engine.save({...saved,action:'checkout',checkoutId:'receipt-1'},(h,b)=>checkout(h,b));assert.equal(done.home.history[0].total,190);assert.equal(done.home.cart.length,0);assert.equal(done.home.products[0].runningLow,false);f.editRemote(h=>h.products[1].notes='remote');f.setOnline(true);await f.engine.load();await f.engine.load();assert.equal(f.remote().home.history.filter(r=>r.id==='receipt-1').length,1);assert.equal(f.remote().home.products[1].notes,'remote');assert.equal(valid(f.remote().home),true);});
